### PR TITLE
AR 5.2: Support polymorphic_name

### PR DESCRIPTION
**Pull request by marshall-lee**
`polymorphic_name` was introduced in 5.2.0 but wasn't properly ported to CPK.

### CODE REVIEW

**Comment by marshall-lee** [comment]
@cfis Hi and thanks for merging of #604 #605 and #606 to support `polymorphic_name` in Rails >= 6!
But one of my codebases is still on 5.2 and this fix is actually crucial there. I humbly ask you please merge the fix into upstream so I can refer to the official repo in my `Gemfile`. I know 5.2 is EOL many years ago but things are not that smooth sometimes, sometimes codebases are stuck with older versions.

**Comment by cfis** [comment]
Yes sure, thought I had merged. Done now.

**Comment by marshall-lee** [comment]
@cfis Hi! Is there a chance `11.x`, `12.x` and `13.x` versions with this fix be released on rubygems?

**Comment by cfis** [comment]
Well I would usually only do 14.x and 13.x  - anything older is unsupported. Do you really need it on all those releases?

**Comment by marshall-lee** [comment]
@cfis i'm in the process of upgrading to 6.1 so 13.x would be fine!

**Comment by cfis** [comment]
Coo, done.

**Pull request merged**
