### PR TITLE
Support ActiveRecord 7.0

### PR DESCRIPTION
**Pull request by codeodor**
* Update dependencies to AR 7.0 + Ruby 2.7

Many more commits to come. If anyone wants to help make the tests pass, please feel free to send PRs to my fork so I can pull them in as I work on them too.

### CODE REVIEW

**Comment by codeodor** [comment]
This might be the quickest time ever to a green suite of tests. Only took me 1.5 hours. 

Still need to update my app to run its tests to be sure there aren't any CPK's suite might have missed.

**Comment by cfis** [comment]
Cool - thanks for pushing this forward!

**Comment by codeodor** [comment]
OK, I think this is ready. My app's tests are all passing now too. What's the process? Make a branch for 13.x off of master, then merge this? What's the release step look like?

**Comment by cfis** [comment]
Thanks @codeodor for doing this! I created a new branch for active record 6.1 and merged your changes. I'm thinking of waiting until Rails 7.0.1 comes to release a new version so we can test it with Ruby 3.1 (Rails 7 currently doesn't work with Ruby 3.1). Also, I'll see if I can update an app I have that makes heavy use of composite primary keys to provide some additional testing.

**Comment by codeodor** [comment]
That would be awesome (if you can test that app). The more surface area we can test, the better! 

Thanks for your continued support of this project, it's been invaluable!

**Comment by cfis** [comment]
Ok, managed to get the app upgraded (that took a couple days, big app). And it worked perfectly, I didn't see any CPK issues at all. Thus I have officially released CPK 14.0.0.

Thanks for making this happen!

**Pull request merged**
