### PR TITLE
Support optimistic lock.

### PR DESCRIPTION
**Pull request by kirikak2**
#257

### CODE REVIEW

**Comment by cfis** [comment]
Sorry for not getting to this before - and thanks for writing up.  Anyway you can use the existing fixtures though for the test cases?  And have you moved to Rails 4.2, should we apply it to that branch?

**Comment by kirikak2** [comment]
No problem. Thank you for your response.
This test case needs lock_version column. However existing fixtures have no lock_version column. Can I add lock_version column to any tables?

This problem occurred in ar_4.1.x branch. (maybe ar_4.2.x branch too).
I want apply this patch to ar_4.1.x and others. What should I do?

**Comment by cfis** [comment]
Yes, feel free to add lock-version column to whichever table(s) you want.  I'm ok with modifying the existing tables, adding/removing test data, etc.  I would just rather avoid adding more tables if its possible.  Of course if its not, then that is ok.

**Comment by kirikak2** [comment]
Thank you. I fixed this, and created new PR #272.
I will check to apply other branches.

**Comment by cfis** [comment]
Ok, great, will close this PR then.

**Pull request closed without merging**
