### PR TITLE
Start AR4.2.4 Compatibility

### PR DESCRIPTION
**Pull request by brgaulin**
This should help #323 and some weird Rails 4.2.4 compatibility issues. For the most part I went and got the updated code from the rails 4.2.4 branch. Most of the changes were from a while ago, small bug fixes, etc. But there were a lot of them =)

I am going to run a bunch of tests locally against a private project and report back if this breaks 4.2.3 or 4.2.4 integrations. If it does we may just need to lock at AR4.2.4 for the next version.

Also you may want to look at this with whitespace off. My editor tends to add newlines at the ends of files and such(if this isn't desired for some reason let me know and I will revert those) but ya, lots of nothing lines changed.

/cc @cfis 
URL for whitespace off: https://github.com/composite-primary-keys/composite_primary_keys/pull/326/files?w=false

Relevant Rails Commits
https://github.com/rails/rails/commit/6cd9e2bd29b26e1ea781fafce18614217b7adf7b
https://github.com/rails/rails/commit/4b534152951fe9b1af8a1d3311da766e1d42392a
https://github.com/rails/rails/commit/9f1b5c9b4032d081f5b7d7fe9697ba24e2ae3ff8
https://github.com/rails/rails/commit/dd8b5fb9d30f355d4eab6376b8d9e025e90b14d3
https://github.com/rails/rails/commit/cb277485f9d78f3661c7103e7b468812cc283223
https://github.com/rails/rails/commit/a58cafeb3a86be46849de57481b6644094fb8165

### CODE REVIEW

**Comment by brgaulin** [comment]
Not sure who watches these. But I would love some feedback on this PR. Mainly around if you think I broke something, or if this is even something we want to do

**Comment by cfis** [comment]
I was actually starting to look at this yesterday.  It seems mostly ok to me, do all tests pass?  We are still on Rails 4.1 so I think its unlikely we will ever use the CPK branch for 4.2 (we will just go to 5.0).

One minor thing, why did you hardcode the mysql gem version?

**Comment by brgaulin** [comment]
Ah. The tests do pass(see travis ci for confirmation) And I ran this against an enterprise 4.2.3 rails app and all of those tests pass as well. Worst case we can lock it to the newer version. But really all I did was look at the 4.2.4 branch of active record and updated some of the CPK methods with the bugs that have been fixed over the past year and commit to the rails repo.

**Comment by brgaulin** [comment]
Sorry I didn't notice the question. The MySQL version failed if I didn't hard code it. Something about the newest MySQL gem being s new minor version that active record doesn't want to support



--Brendan Gaulin

(508) 728-3582

**Comment by cfis** [comment]
I went ahead and merged this - thanks!  I think we should clean up the mysql issue if possible.

**Pull request merged**
