### PR TITLE
Fix database setup and tests for Oracle #327

### PR DESCRIPTION
**Pull request by skatscher**
This pull request should help to fix database setup and test for Oracle as stated in issue #327. Please check pull request.

Thank you & best regards
skatscher

### CODE REVIEW

**Comment by skatscher** [comment]
Latest Travis CI build was successfull. 
Please check pull request.

**Comment by skatscher** [comment]
I successfully ran tests for oracle_enhanced adapter locally. The tests for others adapters mysql, postgresql and sqlite3 were sucessfully checked by Travis CI.

@cfis Can you please check the pull request. Would be great to have it also merged to ar_4.2 branch.

**Comment by skatscher** [comment]
@cfis: Have you already had time to look at the pull request? Do you have remarks?
Thanks and best regards!

**Comment by cfis** [comment]
Happy to apply, but this pull request no longer cleanly applies.  Could you fix it up and then I'll apply it?

**Comment by cfis** [comment]
Never mind, was easy to fix, committed.

**Comment by skatscher** [comment]
@cfis: Thank you!
However, I am wondering that Travis CI build 30 fails:
https://travis-ci.org/composite-primary-keys/composite_primary_keys/builds/87280934
And merge commit shows changes in file lib/composite_primary_keys/composite_predicates.rb, where I did not make any changes. Did you make those changes purposely?

**Pull request merged**
