### PR TITLE
Update for rails 5.1.5 support

### PR DESCRIPTION
**Pull request by tomhughes**

### CODE REVIEW

**Comment by edsharp** [comment]
Nice Tom - it WFM :)

**Comment by kevgrig** [comment]
This PR also fixes an issue I had with:

```
#<ArgumentError: wrong number of arguments (given 1, expected 2)>
        /home/kevin/.gem/ruby/bundler/gems/composite_primary_keys-87de37993cf1/lib/composite_primary_keys/associations/join_dependency.rb:21:in `instantiate'
        /home/kevin/.gem/ruby/gems/activerecord-5.1.5/lib/active_record/relation.rb:674:in `block in exec_queries' [...]
```

Gemfile:

    gem "composite_primary_keys", github: "tomhughes/composite_primary_keys", branch: "ar_5.1.5"

**Comment by letrungkien** [comment]
Wonderful

**Comment by cfis** [comment]
Thanks!

**Pull request merged**
