### PR TITLE
Upgrading CPK to Work With Rails 5

### PR DESCRIPTION
**Pull request by codeodor**
Just as an FYI, I'm working on it, so if others are, let's try not to duplicate work. :smile: 

References #332

### CODE REVIEW

**Comment by codeodor** [comment]
This will be a slow process as I work through the errors in my app. Some will be CPK, some will be other gems. After I get the app's tests passing, I'll work on the CPK test suite.

**Comment by cfis** [comment]
Sounds good - thanks for tackling this.  We will also update our app, but it likely not for a few more months.

**Comment by codeodor** [comment]
Got my apps tests down to only 6 failures, none of which I think are CPK related.

Unfortunately, my test suite is now running 36+ minutes, and it was certainly not even in double digits of minutes before now. Because of how long it takes to run, I don't know if I'm gonna make a lot of progress in determining if those 6 failures are CPK-related or not.

I don't yet know if the huge performance hit is CPK-related or due to changes in Rails itself.

There are a lot of deprecation notices that I'm considering working on next. 

It's going to be hard to untangle all them though. A ton (maybe all?) run through one part of CPK, but that's not where the deprecation notice is coming from ... it's just calling `#to_a` on the relation, which finally executes it after who knows where it came from, so :sob:

**Comment by codeodor** [comment]
Decided to go ahead and knock out some of the CPK gem test failures. So far:

mysql: `171 runs, 369 assertions, 13 failures, 20 errors, 0 skips` 
postgresql: `171 runs, 364 assertions, 9 failures, 23 errors, 0 skips`
sqlite3: `171 runs, 364 assertions, 9 failures, 23 errors, 0 skips`

**Comment by codeodor** [comment]
I found out today that the issue with performance I was seeing was fixed in `rails/master`, so it's good I don't have to look into that any further!

**Comment by cfis** [comment]
Nice!

**Comment by codeodor** [comment]
TODO: Need to test Rails without CPK to see if it autosaves associations even when there are no changes to the "parent" model.

Our tests expect it, but I had to add in a fake call to `<random_attribute>_will_change!` to make it work.

**Comment by codeodor** [comment]
Progress is slow, but moving forward a bit:

```
mysql: 171 runs, 389 assertions, 9 failures, 13 errors, 0 skips
postgresql: 171 runs, 384 assertions, 5 failures, 16 errors, 0 skips
sqlite3: 171 runs, 384 assertions, 5 failures, 16 errors, 0 skips
```

**Comment by codeodor** [comment]
@cfis, can you help me understand [what this was intended to fix](https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/composite_predicates.rb#L11-L27)?

It seems to break when there are more than two columns making up a composite key, so I rewrote it to not do that in this work (just needed to set the return variable from the call to `inject`) since it was not modifying in place). 

However, even with my "fix" it breaks if you are looking up multiple records at a time, because it results in something like this:

`where id1 = 1 and id2 = 2 or id1 = 3 and id2 = 4`  (since it does not group them first)

I want to go back to the original implementation since that is indeed what it should be doing, but I wanted to bring it up in case there's something else that needs to be done to account for what it was intended to do.

**Comment by codeodor** [comment]
Probably stopping for today, but still a bit closer:

```
mysql: 171 runs, 401 assertions, 6 failures, 8 errors, 0 skips
postgresql: 171 runs, 394 assertions, 4 failures, 11 errors, 0 skips
sqlite3: 171 runs, 394 assertions, 4 failures, 11 errors, 0 skips
```

**Comment by codeodor** [comment]
```
mysql: 172 runs, 409 assertions, 5 failures, 5 errors, 0 skips
postgresql: 172 runs, 402 assertions, 3 failures, 8 errors, 0 skips
sqlite3: 172 runs, 402 assertions, 3 failures, 8 errors, 0 skips
```

A tiny bit more progress today. I suspect all but one of those issues are due to:

1. Somewhere we're not splitting the keys into separate clauses (` where id1, id2 = 3, 4` as an example)
2. `#build` is not setting the keys on an association

The last issue is something weird with `#create` which may be related to number 2 above, now that I think about it.

**Comment by codeodor** [comment]
```
mysql: 174 runs, 424 assertions, 5 failures, 0 errors, 0 skips
postgresql: 174 runs, 417 assertions, 3 failures, 3 errors, 0 skips
sqlite3: 174 runs, 417 assertions, 3 failures, 3 errors, 0 skips
```

**Comment by codeodor** [comment]
OK, we're all green now, so at least I suppose we should feel relatively safe in upgrading.

Still need to figure out what's causing the deprecation notices though. That's a tough one, because it happens somewhere with how we build the queries, and I think it never makes its way into the call stackif you were to print the whole thing from the deprecation. :cry:

**Comment by codeodor** [comment]
:warning: Reviewing my app's test failures, I'm seeing a couple that lead me to believe part of CPK is interfering with the "normal" Rails operation of non-composite keys. Just wanted to note this here to hopefully remind me to review it, and as a warning against anyone using this in its current state.

**Comment by codeodor** [comment]
There are still deprecations and warnings, but I found one major source of them today. That one was a LOOOONG time coming. Funny that when I'm just about ready to give up (here and elsewhere), I remember there is one last source I can turn to for answers: `set_trace_func`

**Comment by codeodor** [comment]
:fireworks: :tada: :balloon: All tests pass on the 3 DBMS I can check, all warnings removed or silenced, all deprecation notices fixed. 

So now I feel comfortable in removing the [WIP] tag. 

@cfis I think this is ready to merge after your review.

We'll likely need to update again as Rails releases more betas or RCs, and then the final version, but at least for now anyone who's working on upgrading their app could have something compatible with current the Rails master branch.

**Comment by cfis** [comment]
Awesome work Sammy!  Will cut a 9.0.0.beta gem.

**Pull request merged**
