### PR TITLE
Update for Rails 5.1

### PR DESCRIPTION
**Pull request by jkowens**
This gets the build passing for Rails 5.1.

### CODE REVIEW

**Comment by assembler** [comment]
I guess this is going to be part of Version 10.x release. Any news on when this is coming out?

**Comment by jkowens** [comment]
@cfis any chance you have time to review this PR for me?

**Comment by pas256** [comment]
@cfis I will gladly donate money for a code review and a 10.x release of this

**Comment by v3rron** [comment]
Currently this gem is the only one that prevents us upgrading to Rails 5.1

**Comment by lanej** [comment]
@cfis can you help us out?

**Comment by cfis** [comment]
Hi all - Sorry for the delay on this.  Will review for sure by end of weekend.

**Comment by pas256** [comment]
@jkowens just got my hopes up then

**Comment by jkowens** [comment]
Sorry that was an accident 😕

**Comment by lanej** [comment]
Maybe it got @cfis attention

**Comment by pre** [comment]
>  Will review for sure by end of weekend.

How long is the weekend in the US? :)

**Comment by wtaysom** [comment]
Perhaps celebrating Mid-Autumn Festival?

**Comment by cfis** [comment]
Yeah, sorry :(  Week got away from me...

**Comment by cfis** [comment]
Sorry for the delay on this. Committed with a bit of modification.

**Pull request merged**
